### ISSUE TITLE
Do all the features of metorikku(v0.0.98）work on spark 2.3.2?

### ISSUE THREAD

**Issue by forestlzj** [YotpoLtd/metorikku#381]
I'd like to get metorikku latest version(v0.0.98) work on an existing hadoop cluster with spark 2.3.2, unluckly with error when writing data to hive. 

```
java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SharedState.externalCatalog()Lorg/apache/spark/sql/catalyst/catalog/ExternalCatalogWithListener;
at com.yotpo.metorikku.output.writers.file.FileOutputWriter.overwriteExternalTable(FileOutputWriter.scala:87)
```

Does metorikku v0.0.98 requires spark 2.4.5 instead of the said spark 2.2+ ?

**Comment by lyogev** [comment]
I guess I haven't testes with spark 2.3 in a while.
Let me see if I can get a fix working for spark 2.3 .
